version: '3.9'


networks:
  proxy_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.88.0.0/16
        gateway: 172.88.0.1


services:
  rust-api:
    container_name: app-rust-2
    image: 1998crtxr/rust-api:v1.2
    build:
      context: .
      args:
        - TARGETPLATFORM=linux/amd64,linux/arm64
    dns:
      - 8.8.8.8
    ports:
      - "18080:8080"
    restart: unless-stopped
    depends_on:
      - clash-server
    environment:
      https_proxy: "http://clash-server:7890"
      HTTPS_PROXY: "http://clash-server:7890"
      http_proxy: "http://clash-server:7890"
      HTTP_PROXY: "http://clash-server:7890"
    networks:
      - proxy_net
    volumes:
      - ./volume/rust_app:/out
  
  clash-server:
    container_name: clash-server-rust 
    image: dreamacro/clash-premium
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "9090:9090"
      - "7890:7890"
    networks:
      - proxy_net
    volumes:
      - "./volume/clash:/root/.config/clash" #只能映射到目录
      # - "./volume/clash/ui:/ui"
    restart: unless-stopped

    